// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq0oTVSm8YWSw9ZwePW5iEYhxkadEXl6E',
    appId: '1:800438050049:web:d9f5634886f9512675cf00',
    messagingSenderId: '800438050049',
    projectId: 'inotes-hsm',
    authDomain: 'inotes-hsm.firebaseapp.com',
    storageBucket: 'inotes-hsm.appspot.com',
    measurementId: 'G-CMSGJQCXJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-C3VM11SA8dQwJDIFFn_qUq76G4uLrs',
    appId: '1:800438050049:android:d739cfc9b38c153d75cf00',
    messagingSenderId: '800438050049',
    projectId: 'inotes-hsm',
    storageBucket: 'inotes-hsm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwUem2n_jHU0rkQxA2FuI6_yiw7tq4STc',
    appId: '1:800438050049:ios:22d846be04ec6a5375cf00',
    messagingSenderId: '800438050049',
    projectId: 'inotes-hsm',
    storageBucket: 'inotes-hsm.appspot.com',
    iosClientId: '800438050049-qjverr5apb467a71evu38c6mjivjenia.apps.googleusercontent.com',
    iosBundleId: 'in.hsmmakingstuff.inotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwUem2n_jHU0rkQxA2FuI6_yiw7tq4STc',
    appId: '1:800438050049:ios:6f0fd08ada335f1e75cf00',
    messagingSenderId: '800438050049',
    projectId: 'inotes-hsm',
    storageBucket: 'inotes-hsm.appspot.com',
    iosClientId: '800438050049-n9qqln6icld2oucf1a7gv2kqda67ps1u.apps.googleusercontent.com',
    iosBundleId: 'in.hsmmakingstuff.inotes.RunnerTests',
  );
}
